USER_INFO_USER_ID in (SELECT REQUISITION_LIST.USER_INFO_USER_ID
FROM REQUISITION_LIST, USER_INFO
WHERE REQUISITION_LIST.USER_INFO_USER_ID=USER_INFO.USER_ID
AND USER_INFO.USER_NAME = :GLOBAL.USER_NAME)
