SELECT ALL REQUISITION_ITEMS.REQ_ITEM_ID, REQUISITION_ITEMS.PRODUCT_ID,(SELECT PRODUCTS.PRODUCT FROM PRODUCTS where PRODUCTS.PROD_ID=REQUISITION_ITEMS.PRODUCT_ID), REQUISITION_ITEMS.UOM_UOM_ID, 
REQUISITION_ITEMS.PRICE, REQUISITION_ITEMS.QTY
FROM REQUISITION_ITEMS 
where REQUISITION_ITEMS.REQ_ITEM_ID not in (select ORDER_ITEMS.REQ_ITEM_ID from ORDER_ITEMS WHERE ORDER_ITEMS.ORDER_LIST_ORDER_LIST_ID = :ORDER_ITEMS_BLK.ORDER_LIST_ORDER_LIST_ID)
ORDER BY 1